services:
  source_db:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_SOURCE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SOURCE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_SOURCE_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - source_data:/var/lib/postgresql/data

  target_db:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_TARGET_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TARGET_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TARGET_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - target_data:/var/lib/postgresql/data

  generate_data:
    build: .
    env_file:
      - .env
    environment:
      - NUM_RECORDS=${NUM_RECORDS:-5000}
    depends_on:
      - source_db
      - target_db
    volumes:
      - ./:/app

  cdc_scripts: 
    build:
      context: .
      dockerfile: ./scripts/Dockerfile
    env_file:
      - .env
    environment:
      - NUM_RECORDS=${NUM_RECORDS:-10}
    depends_on:
      - source_db
    volumes:
      - ./scripts:/app/scripts

volumes:
  source_data:
  target_data: